# Site settings
title: MetaTrader 交易平台编程教程
email: theseusyang@gmail.com
description: "MetaTrader 交易平台编程入门，编程详解示例"
baseurl: ""
url: "http://mt4tutorial.github.io"
twitter_username: mt4tutorial
github_username:  mt4tutorial

# Build settings
markdown: kramdown
permalink: pretty
